name: NodeJS with Webpack

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run start

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
